### PR TITLE
FIX: Can't style icons with :class attribute

### LINKED ISSUE #43: Can't style icons with :class attribute
I'm unable to style an icon by passing a :class to the component.

```vue
<template>
  <div>
    <circle-icon 
      :class="{'active': true}" 
    />
  </div>
</template>
```

The resulting `<span>` will not include "active".

This seems to be related to #30

### PR DESCRIPTION
**Pull request by TomerPacific**
Fixes #43 

Following @therufa comment, I have added a fallback to the class attribute in the template file.

### CODE REVIEW

**Comment by TomerPacific** [comment]
@therufa , can you please let me know if this PR is what you wanted.

**Comment by therufa** [comment]
@TomerPacific, I didn't look into the issue originally, but it seems that it should work just fine anyway. However, I accepted the PR, but it needs some investigation. Thanks for your efforts so far!

**Comment by TomerPacific** [comment]
@therufa , I can help in the investigation, if needed.

**Comment by robertfausk** [comment]
Any news on this?:)
Where is it hanging?

**Pull request closed without merging**
